language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/fqn-check src

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
